### PR TITLE
fix link to template-arts @ FAU

### PR DESCRIPTION
**Pull request by ausgerechnet**
changed the README so the link to the magnificent copyrighted artwork of FAU points to the right website, since I just spent half an hour looking for it.

### CODE REVIEW

**Comment by TimRoith** [comment]
Perfect,
thanks for this fix and sorry for the inconvenience.

**Comment by ausgerechnet** [comment]
great, and thx for this repository!

as an afterthought: I just realized that one can download the artwork from the website without being logged in to the uni network. does this mean you could also just put them into this repository?

**Comment by TimRoith** [comment]
That is interesting and I am pretty sure it is by accident. The last time I was in contact with someone from the FAU corporate team, they were really clear about the distribution rules, therefore I'm hesitant to upload them here. 

I am not a fan of the solution right now myself, but I hope it will change in the future, so that files can be just uploaded here. Maybe I can work it out.

**Comment by TimRoith** [comment]
FYI: after quite some time I am finally allowed to upload the logo files here. This should make working with this repo a lot easier.

**Pull request merged**
